### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by redxpwin** [goncy/next-mercadopago#1]
Hola,

Estamos buscando un desarrollador con experiencia en Next.js 14 para que nos ayude a completar un proyecto en el que estamos trabajando. ¿Te gustaría participar? ¿Contás con disponibilidad para unirte?

Si te interesa y querés más detalles, podés contactarme por WhatsApp al: +54 9 11 3494 3000.

¡Muchas gracias y saludos!

**Comment by goncy** [comment]
Gracias @redxpwin pero no estoy interesado, lo que si un consejo no dejes tu whatsapp en un issue de github 😂, saludos!

**Comment by redxpwin** [comment]
Bueno gracias jajaja porque decís lo de wp?

**Comment by goncy** [comment]
@redxpwin los issues se indexan en motores de busqueda, tu whatsapp va a aparecer ahí y hay muchos bots que capturan esos datos y te puede llegar spam / estafas

**Comment by redxpwin** [comment]
uh gracias
