### ISSUE TITLE
suscripcion con pan asocidado

### ISSUE THREAD

**Issue by lucaspieran** [goncy/next-mercadopago#2]
Buenas estoy intentando integrar suscripciones en mi apicacion, la genero a traves de `https://api.mercadopago.com/preapproval_plan` y envio el `init_point` para que genere el pago en el checkout e tema es que si se aprueba el pago no tengo manera de identificar a mi user_id con la suscripcion. Entiendo que se hace a traves del back_url pero quiero contemplar la posibilidad de que la persona cierre la aplicacion de mercado pago y no se complete el back me quedaria un pago sin identificar
```js
{
  "reason": "Esto es un test",
  "auto_recurring": {
    "frequency": 1,
    "frequency_type": "months",
    "repetitions": 12,
    "billing_day": 10,
    "billing_day_proportional": false,
    "external_reference": "YG-1234",
    "free_trial": {
      "frequency": 1,
      "frequency_type": "months"
    },
    "transaction_amount": 15,
    "currency_id": "ARS"
  },
  "payment_methods_allowed": {
    "payment_types": [
      {
        "id": "credit_card"
      }
    ],
    "payment_methods": [
      {
        "id": "bolbradesco"
      }
    ]
  },
  "back_url": "https:/...../checkout"
}
```

**Comment by goncy** [comment]
Ese es uno de los motivos por el que no usé con plan asociado, como la preferencia del plan se crea de antemano no tenés formar de identificar al usuario (porque no existe todavía). Si haces con plan asociado pero usas checkout bricks, podés obtener el card token y usar eso para pagar el plan y ahí si vas a poder identificar al usuario. Para mi es mas fácil usar sin plan asociado y ya

**Comment by lucaspieran** [comment]
@goncy si el tema es que con pago pendiente, el `payer_email` que se envia debe coincidir con e de la cuenta de mercado pago si no te lo rechaza. Y no hay forma de saber eso

**Comment by goncy** [comment]
Si estás logeado con MP no te lo debería pedir asumo, pero en todo caso usá el de plan asociado con checkout bricks y deberías estar bien. Ahí como el pago se procesa en el momento podés actuar directamente! El código es el mismo que usamos en checkout bricks solo que en vez de crear un payment haces el del preapproved plan pasandole el token de la tarjeta

**Comment by ignacionorambuena** [comment]
Hola Goncy, tendrás algún ejemplo con checkout bricks? @lucaspieran conseguiste la solución? Estoy pasando por lo mismo :(
